import { FC } from "react";
import IconProps from "./IconProps";
export type IconType = FC<IconProps>;

export { default as X } from "./X";
export { default as YouTube } from "./YouTube";
export { default as Ostrich } from "./Ostrich";
export { default as Heart } from "./Heart";
export { default as GitHub } from "./GitHub";
export { default as Extension } from "./Extension";
export { default as LightningCharge } from "./LightningCharge";
export { default as ChevronDown } from "./ChevronDown";
export { default as ChevronUp } from "./ChevronUp";
export { default as Note } from "./Note";
export { default as Blog } from "./Blog";
export { default as Search } from "./Search";
export { default as Tag } from "./Tag";
export { default as BinX } from "./BinX";
export { default as User } from "./User";
export { default as Bookmark } from "./Bookmark";
export { default as Linkedin } from "./Linkedin";
export { default as Twitter } from "./Twitter";
export { default as ArrowBarRight } from "./ArrowBarRight";
export { default as Link } from "./Link";
export { default as Facebook } from "./Facebook";
export { default as Dots } from "./Dots";
export { default as PatchCheck } from "./PatchCheck";
export { default as ClipboardCheck } from "./ClipboardCheck";
export { default as ClipboardX } from "./ClipboardX";
export { default as ClipboardCopy } from "./ClipboardCopy";
