export const editorTheme = {
  autocomplete: "absolute bg-white border rounded-md shadow-lg p-2",
  blockCursor: "bg-black",
  characterLimit: "text-gray-500 text-xs",
  code: "bg-gray-100 rounded p-2 font-mono text-sm",
  codeHighlight: {
    atrule: "text-blue-600",
    attr: "text-purple-500",
    boolean: "text-red-600",
    builtin: "text-indigo-600",
    cdata: "text-green-600",
    char: "text-orange-500",
    class: "text-blue-700",
    "class-name": "text-blue-700",
    comment: "text-gray-400",
    constant: "text-red-600",
    deleted: "text-red-700 line-through",
    doctype: "text-gray-400 italic",
    entity: "text-yellow-600",
    function: "text-blue-600",
    important: "text-pink-500 font-bold",
    inserted: "text-green-600 underline",
    keyword: "text-purple-500 font-bold",
    namespace: "text-pink-500 italic",
    number: "text-red-500",
    operator: "text-yellow-600",
    prolog: "text-gray-400",
    property: "text-green-500",
    punctuation: "text-gray-600",
    regex: "text-green-500 underline",
    selector: "text-blue-600",
    string: "text-green-600",
    symbol: "text-red-500",
    tag: "text-red-600",
    url: "text-blue-500 underline",
    variable: "text-yellow-600",
  },
  embedBlock: {
    base: "border rounded-md p-2",
    focus: "border-blue-500 shadow",
  },
  hashtag: "text-sky-400/80 font-bold",
  heading: {
    h1: "text-3xl font-bold mb-2 mt-3",
    h2: "text-2xl font-bold mb-2 mt-3",
    h3: "text-xl font-bold mb-2 mt-3",
    h4: "text-lg font-bold mb-2 mt-3",
    h5: "text-lg font-bold mb-2 mt-3",
    h6: "text-lg font-bold mb-2 mt-3",
  },
  hr: "border-t my-4",
  image: "rounded shadow",
  indent: "ml-4",
  inlineImage: "inline-block rounded shadow",
  layoutContainer: "grid gap-4",
  layoutItem: "p-4 border rounded-md",
  link: "text-sky-400/80",
  list: {
    checklist: "space-y-2",
    listitem: "list-disc",
    listitemChecked: "line-through text-gray-400",
    listitemUnchecked: "text-black",
    nested: {
      listitem: "ml-4 list-square",
    },
    olDepth: [
      "list-decimal ml-4",
      "list-decimal ml-8",
      "list-decimal ml-12",
      "list-decimal ml-16",
      "list-decimal ml-20",
    ],
    ul: "list-disc ml-4",
  },
  ltr: "text-left",
  mark: "bg-yellow-200",
  markOverlap: "bg-yellow-300",
  paragraph: "leading-relaxed",
  quote: "border-l-4 pl-4 italic text-gray-600",
  rtl: "text-right",
  specialText: "text-indigo-600 font-semibold",
  tab: "inline-block w-4 h-4 bg-gray-200",
  table: "table-auto border-collapse w-full",
  tableCell: "border p-2",
  tableCellActionButton: "text-blue-500 cursor-pointer",
  tableCellActionButtonContainer: "flex items-center justify-center",
  tableCellHeader: "bg-gray-200 font-bold p-2",
  tableCellResizer: "cursor-col-resize",
  tableCellSelected: "bg-blue-100",
  tableRowStriping: "odd:bg-gray-100 even:bg-white",
  tableScrollableWrapper: "overflow-x-auto",
  tableSelected: "bg-blue-200",
  tableSelection: "bg-blue-100",
  text: {
    // base: "",
    bold: "font-bold",
    capitalize: "capitalize",
    code: "font-mono text-sm bg-muted p-1 rounded",
    italic: "italic",
    lowercase: "lowercase",
    strikethrough: "line-through",
    subscript: "align-sub text-xs",
    superscript: "align-super text-xs",
    underline: "underline",
    underlineStrikethrough: "underline line-through",
    uppercase: "uppercase",
  },
};

